name: Mis Workflows
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: Ejecutar comando antes de la accion
        run: ls -la

      - name: Actions Example
        uses: actions/checkout@v4

      - name: Ejecutar comando despues de la accion
        run: ls -la

      - name: Working dir
        id: step_1
        run: echo "my_variable=Esta todo OK" >> $GITHUB_OUTPUT

      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"

  second-job:
    needs: first-job
    env:
     nombre: Codigo Facilito
     salida: ${{ needs.first-jobs.outputs.salida }}
    if: true
    
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo $nombre"
      - name: Imprimir salida
        run: echo "$salida"