name: Mis Workflows
on:
 # - push            # Se activa cuando hay un 'push' al repositorio
 # - pull_request    # Se activa cuando hay un 'pull request'
  - workflow_dispatch # Se activa manualmente desde GitHub Actions

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar comando antes de la accion
        run: ls -la

      - name: Actions Example
        uses: actions/checkout@v4

      - name: Ejecutar comando despues de la accion
        run: ls -la

      - name: Working dir
        id: step_1
        run: echo "my_variable=Esta todo OK" >> $GITHUB_OUTPUT

      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"

      - name: Generar archvo
        run: |
          echo "Este es un archivo de prueba" >> test.log

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

  second-job:
    needs: first-job
    env:
     nombre: Codigo Facilito
     salida: ${{ needs.first-job.outputs.salida }}
    if: true
    
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo $nombre"

      - name: Imprimir salida
        run: echo "$salida"
    
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-test

      - name: Cat archivo
        run: cat test.log