name: Mis Workflows
on: push

jobs:
  fisrt-job:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar comando antes de la accion
        run: ls -la 
      - name: Actions Example
        run: actions/checkout@v4
      - name: Ejecutar comando despues de la accion
        run: ls -la

  second-job:
    env:
        VAR: Codigo Facilito
    if: true
    needs: fisrt-job
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo $VAR"